add blog
neume-network/website pull request #2
Opened 2022-05-17 20:57 UTC by il3ven

This PR adds blog functionality using 11ty and EleventyDuo theme. Fixes #1.

### Changes:

#### Fix for GitHub Page
The theme is now deployable to Github pages. Github hosts pages at `user.github.io/repo` so links break. For example a link to `/posts` will point to `user.github.io/posts` instead of `user.github.io/repo/posts`. This was one of the fix.

#### Comment unnecessary code
I have commented out [mermaid](https://www.npmjs.com/package/mermaid) which is a diagramming tool. This reduces bundle size by 300kb.

#### Personalise Blog
I have personalised the blog i.e mention neume-network and change social links. `src/data/site.json` contains many constants.

#### Add workflow to deploy to Github Pages
I have added a workflow to deploy to gh pages. In order for Github pages to work on neume-network/website repo there are a few steps:
- Enable Github pages from settings
- Select gh-pages as the branch and root as the directory
- Create a gh-pages manually. The workflow doesn't have permission to create new branches. It can only update.

I can do the above steps but I will need access to the repo.

### Further Changes

We can still personalise it more. Change the text on the welcome or about page. We can even add new pages or change some css styling. Let me know if any further changes are required. We can open new issues for that. Though in the current state the blog does good. Anymore changes will be subjective.

2022-05-17 21:11 UTC, TimDaub requested changes
- It looks clean, and also I like that the page has a small footprint :)
- A minor legal annoyance: For the EU, Google Fonts isn't GDPR compliant by default: https://usercentrics.com/knowledge-hub/google-fonts-gdpr-compliant/
  - I recommend finding either a web-safe font similar to what we're already using or vendoring in the font as shown in the article above.
  - Alternative is including a cookie banner (which I'd like to avoid)

2022-05-17 21:17 UTC, il3ven commented
> A minor legal annoyance: For the EU, Google Fonts isn't GDPR compliant by default.

I'll look into this.

I also found that the sitemap isn't working. This [problem](https://eleventyduo.netlify.app/sitemap.xml) is present in the theme too. I'll look into this too.

2022-05-18 08:10 UTC, TimDaub commented on src/layouts/base.njk
> +    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap" rel="stylesheet">
replace bc of gdpr

2022-05-18 08:12 UTC, TimDaub commented on src/css/typography.css
> +  font-family: 'IBM Plex Sans', sans-serif;
Where is this one loaded from?

2022-05-18 09:25 UTC, reimertz commented
Thanks @TimDaub for bringing up not using Google fonts. 

On that note,I have setup a Cloudflare worker to enable a [Plausible.io](https://plausible.io) proxy for a privacy-first, GDPR-complaint cookieless analytics. 

All we have to do is to add a script tag with `https://neume.network/neume/js/info.js` and everything else should work as intended.

2022-05-18 09:27 UTC, TimDaub commented
> On that note,I have setup a Cloudflare worker to enable a [Plausible.io](https://plausible.io) proxy for a privacy-first, GDPR-complaint cookieless analytics.

That's awesome! Thanks!

2022-05-18 09:41 UTC, reimertz commented
I took the liberty of connecting this repo to Netlify for smooth preview deploy integration. So hopefully, the next commit will generate a preview link. 

Once the site is deployed, I'll help setting up Cloudflare cache purge so the site can be proxied by Cloudflare CDN with aggressive cache, but then purged once new deploys happen.

2022-05-18 11:04 UTC, reimertz commented
Netlify preview deploys seems to be working smoothly now.

2022-05-18 14:15 UTC, djfnd commented
Apologies, I missed the PR previously.
Font-wise, we are running under the assumption of Helvetica for the design work that is ongoing, if that helps.

2022-05-18 22:13 UTC, TimDaub approved these changes
great job @il3ven!

2022-05-18 22:13 UTC, merged